name: pytorch
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - comm=0.2.3
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.0.18
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - accelerate==0.24.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - anndata==0.11.4
      - array-api-compat==1.12.0
      - asciitree==0.3.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - biopython==1.85
      - captum==0.8.0
      - certifi==2022.12.7
      - chardet==4.0.0
      - charset-normalizer==2.1.1
      - circlify==0.15.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - fasteners==0.20
      - filelock==3.13.1
      - fonttools==4.60.1
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - h5py==3.15.0
      - hf-xet==1.1.10
      - hnswlib==0.8.0
      - huggingface-hub==0.35.3
      - idna==2.10
      - jinja2==3.1.4
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - legacy-api-wrap==1.4.1
      - lightning-utilities==0.15.2
      - llvmlite==0.45.1
      - loguru==0.7.3
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - multidict==6.6.4
      - natsort==8.4.0
      - networkx==3.3
      - numba==0.62.1
      - numcodecs==0.13.1
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.7.0.84
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.19.3
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - obonet==1.1.1
      - pandas==2.2.2
      - patsy==1.0.1
      - pillow==11.0.0
      - propcache==0.3.2
      - psutil==7.1.0
      - pyarrow==22.0.0
      - pyg-lib==0.4.0+pt22cpu
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - pytorch-lightning==2.5.5
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.9.18
      - requests==2.25.1
      - rpds-py==0.28.0
      - safetensors==0.6.2
      - scanpy==1.10.2
      - scikit-learn==1.7.2
      - scimilarity==0.4.1
      - scipy==1.14.1
      - seaborn==0.13.2
      - sentencepiece==0.2.1
      - session-info==1.0.1
      - statsmodels==0.14.5
      - stdlib-list==0.11.1
      - sympy==1.13.3
      - tblib==3.2.1
      - threadpoolctl==3.6.0
      - tiledb==0.35.1
      - tiledb-cloud==0.14.3
      - tiledb-vector-search==0.15.0
      - tokenizers==0.13.3
      - torch==2.2.2+cu118
      - torch-cluster==1.6.3+pt22cpu
      - torch-geometric==2.7.0
      - torch-scatter==2.1.2+pt22cpu
      - torch-sparse==0.6.18+pt22cpu
      - torch-spline-conv==1.2.2+pt22cpu
      - torchaudio==2.2.2+cu118
      - torchmetrics==1.8.2
      - torchvision==0.17.2+cu118
      - tqdm==4.66.5
      - transformers==4.30.2
      - triton==2.2.0
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - urllib3==1.26.6
      - xxhash==3.6.0
      - yarl==1.20.1
      - zarr==2.18.3
prefix: /home/a2236013/miniconda3/envs/pytorch
